"""initial schema

Revision ID: 5c188d55ae7c
Revises: 
Create Date: 2026-05-20 21:10:14.618360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c188d55ae7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_quota_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('requests_remaining', sa.Integer(), nullable=True),
    sa.Column('requests_used', sa.Integer(), nullable=True),
    sa.Column('requests_limit', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_quota_log', schema=None) as batch_op:
        batch_op.create_index('idx_aql_provider', ['provider', 'captured_at'], unique=False)

    op.create_table('bankroll_book_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('book_code', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('deposits_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('withdrawals_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stakes_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('payouts_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('picks_placed_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('picks_won_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('picks_lost_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pnl_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'book_code', name='uq_bbs_date_book')
    )
    with op.batch_alter_table('bankroll_book_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_bbs_date', ['snapshot_date'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('odds_api_id', sa.String(), nullable=True),
    sa.Column('api_football_id', sa.Integer(), nullable=True),
    sa.Column('league_key', sa.String(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('commence_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_goals_ht', sa.Integer(), nullable=True),
    sa.Column('away_goals_ht', sa.Integer(), nullable=True),
    sa.Column('total_corners', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'live', 'finished', 'cancelled', 'postponed')", name='ck_events_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odds_api_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_commence', ['commence_time'], unique=False)
        batch_op.create_index('idx_events_league', ['league_key'], unique=False)
        batch_op.create_index('idx_events_status', ['status'], unique=False)

    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('metadata', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.create_index('idx_oplog_level', ['level'], unique=False)
        batch_op.create_index('idx_oplog_occurred', ['occurred_at'], unique=False)

    op.create_table('system_state',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_paused', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('paused_reason', sa.String(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('last_pipeline_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_settlement_run_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_system_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('bookmaker_key', sa.String(), nullable=False),
    sa.Column('market_key', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_odds_captured', ['captured_at'], unique=False)
        batch_op.create_index('idx_odds_event_market', ['event_id', 'market_key'], unique=False)

    op.create_table('picks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('market_key', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('reference_book', sa.String(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('reference_prob', sa.Float(), nullable=False),
    sa.Column('devigging_method', sa.String(), nullable=False),
    sa.Column('comparison_book', sa.String(), nullable=False),
    sa.Column('comparison_price', sa.Float(), nullable=False),
    sa.Column('min_odds_for_value', sa.Float(), nullable=False),
    sa.Column('ev_at_comparison', sa.Float(), nullable=False),
    sa.Column('kelly_fraction', sa.Float(), nullable=False),
    sa.Column('stake_recommended', sa.Integer(), nullable=False),
    sa.Column('stake_pct_of_bankroll', sa.Float(), nullable=False),
    sa.Column('bankroll_at_generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_date', sa.Date(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_book', sa.String(), nullable=True),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('actual_stake', sa.Integer(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('pnl', sa.Integer(), nullable=True),
    sa.Column('clv', sa.Float(), nullable=True),
    sa.Column('closing_pinnacle_price', sa.Float(), nullable=True),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'placed', 'skipped', 'won', 'lost', 'pushed', 'void')", name='ck_picks_status'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.create_index('idx_picks_event', ['event_id'], unique=False)
        batch_op.create_index('idx_picks_generated', ['generated_at'], unique=False)
        batch_op.create_index('idx_picks_status', ['status'], unique=False)
        batch_op.create_index('idx_picks_unique_no_line', ['event_id', 'market_key', 'outcome', 'generated_date'], unique=True, sqlite_where=sa.text('line IS NULL'))
        batch_op.create_index('idx_picks_unique_with_line', ['event_id', 'market_key', 'outcome', 'line', 'generated_date'], unique=True, sqlite_where=sa.text('line IS NOT NULL'))

    op.create_table('bankroll_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('book_code', sa.String(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('related_pick_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint("movement_type IN ('deposit', 'withdrawal', 'bet_stake', 'bet_payout', 'adjustment')", name='ck_bm_movement_type'),
    sa.ForeignKeyConstraint(['related_pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bankroll_movements', schema=None) as batch_op:
        batch_op.create_index('idx_bm_book', ['book_code', 'occurred_at'], unique=False)
        batch_op.create_index('idx_bm_pick', ['related_pick_id'], unique=False)
        batch_op.create_index('idx_bm_type', ['movement_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankroll_movements', schema=None) as batch_op:
        batch_op.drop_index('idx_bm_type')
        batch_op.drop_index('idx_bm_pick')
        batch_op.drop_index('idx_bm_book')

    op.drop_table('bankroll_movements')
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_index('idx_picks_unique_with_line', sqlite_where=sa.text('line IS NOT NULL'))
        batch_op.drop_index('idx_picks_unique_no_line', sqlite_where=sa.text('line IS NULL'))
        batch_op.drop_index('idx_picks_status')
        batch_op.drop_index('idx_picks_generated')
        batch_op.drop_index('idx_picks_event')

    op.drop_table('picks')
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_odds_event_market')
        batch_op.drop_index('idx_odds_captured')

    op.drop_table('odds_snapshots')
    op.drop_table('system_state')
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index('idx_oplog_occurred')
        batch_op.drop_index('idx_oplog_level')

    op.drop_table('operation_log')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_status')
        batch_op.drop_index('idx_events_league')
        batch_op.drop_index('idx_events_commence')

    op.drop_table('events')
    with op.batch_alter_table('bankroll_book_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_bbs_date')

    op.drop_table('bankroll_book_snapshots')
    with op.batch_alter_table('api_quota_log', schema=None) as batch_op:
        batch_op.drop_index('idx_aql_provider')

    op.drop_table('api_quota_log')
    # ### end Alembic commands ###
