"""add pending_sheets_sync

Revision ID: 80f0759a2448
Revises: 82dac86fd3e0
Create Date: 2026-05-23 11:59:34.868952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f0759a2448'
down_revision: Union[str, Sequence[str], None] = '82dac86fd3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_sheets_sync',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payload_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("payload_type IN ('pick', 'movement', 'bankroll_snapshot')", name='ck_pss_payload_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_sheets_sync', schema=None) as batch_op:
        batch_op.create_index('idx_pss_pending', ['created_at'], unique=False, sqlite_where=sa.text('completed_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_sheets_sync', schema=None) as batch_op:
        batch_op.drop_index('idx_pss_pending', sqlite_where=sa.text('completed_at IS NULL'))

    op.drop_table('pending_sheets_sync')
    # ### end Alembic commands ###
