"""add sharp_overround to picks

Revision ID: 82dac86fd3e0
Revises: 5c188d55ae7c
Create Date: 2026-05-22 18:12:29.006456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dac86fd3e0'
down_revision: Union[str, Sequence[str], None] = '5c188d55ae7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sharp_overround', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_column('sharp_overround')

    # ### end Alembic commands ###
