"""Test de integración: la migración Alembic debe coincidir con los modelos."""
from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config

from betting_bot.config import get_settings

_REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.mark.integration
def test_migrations_in_sync_with_models(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`alembic check` falla si los modelos divergieron de las migraciones.

    Corre sobre una DB temporal. Los tests unitarios usan `create_all()` (el
    schema sale de los modelos), así que NO detectarían que alguien tocó
    `models.py` sin regenerar la migración. Este test cierra ese hueco.
    """
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path / 'drift.db'}")
    get_settings.cache_clear()
    try:
        cfg = Config(str(_REPO_ROOT / "alembic.ini"))
        cfg.set_main_option(
            "script_location", str(_REPO_ROOT / "src/betting_bot/persistence/migrations")
        )
        command.upgrade(cfg, "head")
        command.check(cfg)  # lanza AutogenerateDiffsDetected si hay drift
    finally:
        get_settings.cache_clear()
